server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona todas as rotas para o Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets com hash no nome
    location ~* \.[0-9a-f]{8}\.(js|css|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
